### PR TITLE
Update 2014-02-10-week-1-materials.md

### PR DESCRIPTION
**Pull request by pliu131**
Fixed some formatting issues

### CODE REVIEW

**Comment by danoc** [comment]
I'll fix these manually. I'm shortening the document a bit because it's a bit long for the average attention span.

**Comment by pliu131** [comment]
I would say don't do that just yet because I have shortened versions of the
materials in Markdown as well that I'm using for my slides.

**Comment by danoc** [comment]
Okay, let me know where I can find them!

**Comment by danoc** [comment]
@pliu131 - Any updates on the shortened versions?

**Pull request closed without merging**
